export interface Product {
  name: string;
  defaultQuantity: number;
  defaultRate: number;
}

export const productCatalog: Product[] = [
  { name: "Web Development Service", defaultQuantity: 1, defaultRate: 500.00 },
  { name: "Website Design", defaultQuantity: 1, defaultRate: 800.00 },
  { name: "Logo Design", defaultQuantity: 1, defaultRate: 200.00 },
  { name: "SEO Consultation", defaultQuantity: 1, defaultRate: 300.00 },
  { name: "Content Writing", defaultQuantity: 10, defaultRate: 50.00 },
  { name: "Social Media Management", defaultQuantity: 1, defaultRate: 1000.00 },
  { name: "Mobile App Development", defaultQuantity: 1, defaultRate: 2000.00 },
  { name: "UI/UX Design", defaultQuantity: 1, defaultRate: 600.00 },
  { name: "Cloud Hosting Setup", defaultQuantity: 1, defaultRate: 150.00 },
  { name: "Database Administration", defaultQuantity: 1, defaultRate: 1200.00 },
  { name: "System Integration", defaultQuantity: 1, defaultRate: 1500.00 },
  { name: "API Development", defaultQuantity: 1, defaultRate: 750.00 },
  { name: "Quality Assurance Testing", defaultQuantity: 1, defaultRate: 400.00 },
  { name: "DevOps Consulting", defaultQuantity: 1, defaultRate: 900.00 },
  { name: "E-commerce Development", defaultQuantity: 1, defaultRate: 1200.00 },
  { name: "WordPress Maintenance", defaultQuantity: 1, defaultRate: 250.00 },
  { name: "Security Audit", defaultQuantity: 1, defaultRate: 800.00 },
  { name: "Data Analytics", defaultQuantity: 1, defaultRate: 1000.00 },
  { name: "Technical Support", defaultQuantity: 1, defaultRate: 300.00 },
  { name: "Training Workshop", defaultQuantity: 1, defaultRate: 450.00 },
  { name: "Consulting Services", defaultQuantity: 1, defaultRate: 600.00 },
  { name: "Graphic Design Package", defaultQuantity: 5, defaultRate: 100.00 },
  { name: "Copywriting Services", defaultQuantity: 20, defaultRate: 30.00 },
  { name: "Photography Package", defaultQuantity: 1, defaultRate: 400.00 },
  { name: "Video Production", defaultQuantity: 1, defaultRate: 1500.00 },
  { name: "Podcast Production", defaultQuantity: 1, defaultRate: 800.00 },
  { name: "Email Marketing Setup", defaultQuantity: 1, defaultRate: 350.00 },
  { name: "Marketing Strategy", defaultQuantity: 1, defaultRate: 1200.00 },
  { name: "Brand Identity", defaultQuantity: 1, defaultRate: 1000.00 },
  { name: "Business Analysis", defaultQuantity: 1, defaultRate: 700.00 },
  { name: "Project Management", defaultQuantity: 1, defaultRate: 900.00 },
  { name: "Virtual Assistant", defaultQuantity: 1, defaultRate: 300.00 },
  { name: "Accounting Services", defaultQuantity: 1, defaultRate: 200.00 },
  { name: "Legal Consultation", defaultQuantity: 1, defaultRate: 500.00 },
  { name: "Insurance Premium", defaultQuantity: 1, defaultRate: 250.00 },
  { name: "Office Supplies", defaultQuantity: 5, defaultRate: 20.00 },
  { name: "Software License", defaultQuantity: 10, defaultRate: 150.00 },
  { name: "Hardware Equipment", defaultQuantity: 1, defaultRate: 1200.00 },
  { name: "Training Materials", defaultQuantity: 1, defaultRate: 150.00 },
  { name: "Consultation Fee", defaultQuantity: 1, defaultRate: 300.00 },
  { name: "Maintenance Contract", defaultQuantity: 1, defaultRate: 600.00 },
  { name: "Support Package", defaultQuantity: 1, defaultRate: 400.00 },
  { name: "Data Migration", defaultQuantity: 1, defaultRate: 1000.00 },
  { name: "Custom Software", defaultQuantity: 1, defaultRate: 3000.00 },
  { name: "Technical Writing", defaultQuantity: 15, defaultRate: 40.00 },
  { name: "Documentation", defaultQuantity: 1, defaultRate: 300.00 },
  { name: "Translation Services", defaultQuantity: 100, defaultRate: 0.15 },
  { name: "Transcription", defaultQuantity: 50, defaultRate: 0.25 },
  { name: "Data Entry", defaultQuantity: 200, defaultRate: 0.10 },
  { name: "Market Research", defaultQuantity: 1, defaultRate: 800.00 },
  { name: "Competitor Analysis", defaultQuantity: 1, defaultRate: 600.00 },
  { name: "User Experience Study", defaultQuantity: 1, defaultRate: 1000.00 },
];